version: '3'

volumes:
  local_postgres_data:

networks:
  proxynet:
    driver: bridge

services:
  db:
    image: postgres
    env_file:
      - .envs/.postgres
    ports:
      - "5432:5432" 
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proxynet

  
  nats:
    image: nats-streaming
    ports:
    - 4222:4222
    networks:
      - proxynet
  
  server:
    build:
      context: .
      dockerfile: compose/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - proxynet
    depends_on:
      - db
      - nats