version: '3'

volumes:
  local_postgres_data:

services:
  db:
    image: postgres
    env_file:
      - .envs/.postgres
    ports:
      - "5432:5432" 
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  nats:
    image: nats-streaming
    ports:
    - 4222:4222
  
  nuts-server:
    image: nats-streaming
    ports:
      - "8222:8222"
    env_file:
      - .envs/.nuts
    depends_on:
      - db